# Uncomment the next line to define a global platform for your project
platform :ios, 13.2

source 'https://github.com/CocoaPods/Specs.git'

def common_pods
  pod 'AlamofireImage', '~> 3.6.0'
  pod 'AlamofireObjectMapper', '~> 5.2.1'
  pod 'Localize-Swift', '~> 3.1.0'
  pod 'IQKeyboardManagerSwift', '~> 6.5'
end 

def app_pods
  pod 'SkeletonView', '~> 1.17.2'
end

target 'marvel-app-swiftui' do
  use_frameworks!
  inhibit_all_warnings!
  common_pods
  app_pods
end

target 'marvel-app-swiftuiTests' do 
  use_frameworks!
  inhibit_all_warnings!
  common_pods
end